# Generated by Django 3.2.8 on 2022-02-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cars',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
