# Generated by Django 3.2.8 on 2022-02-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_cars_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='image',
            field=models.ImageField(upload_to='media/blog_images'),
        ),
    ]
