# Generated by Django 3.2.8 on 2022-02-28 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0015_auto_20220228_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='description1',
            new_name='extra1',
        ),
        migrations.RenameField(
            model_name='cars',
            old_name='description10',
            new_name='extra10',
        ),
        migrations.RenameField(
            model_name='cars',
            old_name='description2',
            new_name='extra2',
        ),
        migrations.RenameField(
            model_name='cars',
            old_name='description3',
            new_name='extra3',
        ),
        migrations.RenameField(
            model_name='cars',
            old_name='description4',
            new_name='extra4',
        ),
        migrations.RenameField(
            model_name='cars',
            old_name='description5',
            new_name='extra5',
        ),
        migrations.RenameField(
            model_name='cars',
            old_name='description6',
            new_name='extra6',
        ),
        migrations.RenameField(
            model_name='cars',
            old_name='description7',
            new_name='extra7',
        ),
        migrations.RenameField(
            model_name='cars',
            old_name='description8',
            new_name='extra8',
        ),
        migrations.RenameField(
            model_name='cars',
            old_name='description9',
            new_name='extra9',
        ),
    ]
