# Generated by Django 3.2.8 on 2022-02-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_auto_20220227_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/blog_images'),
        ),
    ]
