# Generated by Django 3.2.8 on 2022-02-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0006_auto_20220227_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='down_payment',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cars',
            name='initial_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cars',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='cars',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
