# Generated by Django 3.2.8 on 2022-02-28 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0009_alter_details_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Details',
        ),
    ]
