# Generated by Django 3.2.8 on 2022-02-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0011_auto_20220228_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
