# Generated by Django 3.2.8 on 2022-02-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0013_alter_postimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='cars',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='cars',
            name='image3',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
